---

# http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
user:
  name: dnewman
  uid: 1002
  group: dnewman
  shell: /bin/bash
  email: dwnewman78@gmail.com
  log:
    dir: log
    rotate: 8

hostname: linuxdev

dotfiles:
  url: git@github.com:floatingman/dotfiles.git
  destination: .dotfiles
  rcup_flags: -fx README.md

aptcachetime: 3600
locale: "en_US.UTF-8"
timezone: "America/Chicago"
chromium:
  set_default: true
  policy: false
  extensions: false
desktop_autostart:
  add:
    - { name: Tilda , exec: /usr/bin/tilda }
  remove:
    - deja-dup-monitor.desktop
    - onboard-autostart.desktop
    - orca-autostart.desktop
    - vino-server.desktop
php_phar_tools:
  php_cs_fixer: true
  phpcpd: true
  sami: true
  robo: true
  phpmd: true
  phpunit: true
  codeception: true
  cssprites: true
  wpcli: true
ssh:
  start: true
  service_enabled: true
  password_auth: false
  root_login: false
  user_key: "{{ ansible_env.HOME }}/ssh/id_rsa"
passwordless_sudo:
  - /usr/bin/openvpn*
vhosts:
  - template: standard
    vhost: "default70.dev"
    path: "{{ ansible_env.HOME }}/projects/default-7.0"
  - template: standard
    vhost: "default56.dev"
    path: "{{ ansible_env.HOME }}/projects/default-5.6"
    php: "5.6"
