---

- name: Install dotfiles dependencies with APT
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  with_items:
    - pwgen
    - imagemagick
    - libav-tools
    - cowsay
    - fortune

# - name: Install dotfiles dependencies with Python PIP
#   pip: name={{ item }} state=latest
#   with_items:
#     - httpie
#     - Pygments

- name: Add rcm repository
  apt_repository: repo="ppa:martin-frost/thoughtbot-rcm" state=present

- name: Install rcm
  apt: pkg=rcm state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  when: dotfiles is defined

- name: Clone user dotfiles
  git: repo={{ dotfiles.url }} dest=/home/{{ user.name }}/.dotfiles accept_hostkey=yes update=no
  when: dotfiles is defined
  become: yes
  become_user: "{{ user.name }}"

- name: Install user dotfiles
  command: rcup {{ dotfiles.rcup_flags }}
  when: dotfiles is defined
  become: yes
  become_user: "{{ user.name }}"
